
import type { Metadata } from "next";
import { Jacquard_24, Texturina } from "next/font/google";
import "./globals.css";

const titleFont = Jacquard_24({ weight: "400", subsets: ["latin"], });

const font = Texturina()

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${titleFont.className} antialiased m-0 p-0 h-screen flex flex-col overflow-hidden`}>
        <header className="h-16 w-full bg-[var(--color-burgundy)] text-[var(--color-parchment)] flex items-center justify-center text-4xl z-50 border-b-4 border-[var(--color-parchment)]">
          Farkle Online
        </header>

        <main className={`${font.className} flex-1 bg-[var(--color-table)] text-3xl text-[var(--color-burgundy)] flex items-center justify-center`}>
          {children}
        </main>

        <footer className="h-16 w-full bg-[var(--color-burgundy)] text-[var(--color-parchment)] flex items-center justify-center text-base z-50 border-t-4 border-[var(--color-parchment)]">
        </footer>
      </body>

    </html>
  );
}

